Using ES6 modules
mariegrace31/Awesomebooks-2 pull request #1
Opened 2023-06-14 21:42 UTC by mariegrace31

In this milestone I:
- Created a new directory and initialized it with git.
- Created a website to add and remove books 
- Used ES6 modules to write modular JavaScript

2023-06-14 22:48 UTC, zieeco requested changes
Hi @mariegrace31,

<img height="200" src="https://media2.giphy.com/media/KmGnZGXkEK34dsIl6X/giphy.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Good commit message.✔️
- Nice using the ES6 syntax. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 22:48 UTC, zieeco commented on modules/add.js
> +function addBook(title, author) {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/add.js
> +export default function handleAddBookFormSubmit(event) {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/booklist.js
> +export default function renderBookList() {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/booklist.js
> +    function removeBook() {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/event.js
> +function handleNavigationLinkClick(event) {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/event.js
> +export default function addEventListeners() {
- Hey, please, kindly use the ES6 arrow function since you're working on learning to use the ES6 syntax.

2023-06-14 22:48 UTC, zieeco commented on modules/add.js
> +  renderBookList();
- Hey, the book doesn't seem to be added when the user adds any book. Please, kindly fix this issue.

2023-06-15 11:47 UTC, rotimiazeez requested changes
Hi @mariegrace31 😉, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 😉
* Books can be added and removed 💪🏽
* Good App UI 👍🏽
* Good PR title 👌🏽

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-06-15 11:47 UTC, rotimiazeez commented on modules/event.js
> +function handleNavigationLinkClick(event) {
Please note that you missed this change. Kindly update it 👍🏽

2023-06-15 12:10 UTC, Eternalgratis requested changes
# Status: Invalid code ❌❌❌
Hi @mariegrace31 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request❌

You have submitted a project, that with linter error. Kindly make adjustments and re-submit when you are ready

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-15 13:16 UTC, topeogunleye approved these changes
### Hi @mariegrace31, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Replaced named function with ES6 arrow function. ✔️ 
- Followed Github flow :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* For future pull requests, please kindly write your branch name in passed tense to show that this changes have already been implemented. For example, you could name your branch `used-es6-modules`. This makes it easier to track the changes and the purpose of each branch.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 13:45 UTC, merged